# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

#.env.default
#fastlane beta version_number:99 build_number:99
#fastlane release version_number:99

default_platform(:ios)

platform :ios do

before_all do
    update_fastlane
    cocoapods(
  		clean: true,
  		podfile: "./Podfile"
	)
end

desc "Run tests"
    lane :tests do
    run_tests(code_coverage:true,
        clean:true,
        workspace: "meuslugares.xcworkspace",
        devices: ["iPhone 5s"],
        scheme: "meuslugaresUITests",
        slack_message:"Successfully run UI Tests")

end

desc "Generate screenshots and upload to apple store"
    lane :screenshots do
        capture_screenshots(scheme: "meuslugares")
        appstore(skip_binary_upload: true,
            skip_metadata: true,
            skip_app_version_update: true,
            force: true,
            overwrite_screenshots: true
        )
        slack(message:"Successfully uploaded screenshots to itunes connect", success:true)
end

desc "Generate metadata"
    lane :metadata do
        appstore(skip_binary_upload: true,
            skip_metadata: false,
            skip_app_version_update: true,
            force: true,
            skip_screenshots:true,
            price_tier: 0,
            app_rating_config_path: "./fastlane/rating_config.json",
            app_icon:"./iTunesArtwork@2x.png"
        )
        slack(message:"Successfully uploaded metadata to itunes connect", success:true)
end

desc "Beta app"
    lane :beta do |options|
        match(type: "appstore", readonly: false)
        increment_version_number(
            version_number: options[:version_number],
            xcodeproj: "meuslugares.xcodeproj"
        )
        increment_build_number(
            build_number: options[:build_number],
            xcodeproj: "meuslugares.xcodeproj"
        )
        changelog = prompt(
            text: "What's new (must be at least 4 characters long): ",
            multi_line_end_keyword: "END"
        )
        build_app(scheme: "meuslugares",
            clean:true,
            workspace: "meuslugares.xcworkspace",
            include_bitcode: true,
            export_method:"app-store"
        )
        pilot(changelog: changelog,
            beta_app_feedback_email:"brunoteixeiralc@gmail.com",
            beta_app_description: "Meus Lugares BETA!",
            distribute_external:true,
            groups: "Testes Externos Meus Lugares"
        )   
        slack(message: "Successfully uploaded to Test Flight",
            success:true)
end


desc "Release app"
    lane :release do
        match(type: "appstore", readonly: true)
        build_app(scheme: "meuslugares",
            clean:true,
            project: "meuslugares.xcodeproj",
            include_bitcode: true,
            export_method:"app-store"
        )
        appstore(skip_metadata:true,
            skip_screenshots:true,
            submit_for_review:true,
            automatic_release:true,
            skip_binary_upload:true
        )
        slack(message: "Successfully uploaded a new App Store build",
            success:true)
end

error do |lane, exception|
    slack(
        message: exception.message,
        success: false
    )
end

end
