# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone X",
#  "iPhone 6",
#  "iPhone 6 Plus",
   "iPhone 5s",
   "iPhone 7",
   "iPhone 7 Plus"
#   "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p"
 ])

languages([
    "en-US"
 ])

# Choose which project/workspace to use
# project "./TecNews.xcodeproj"
 workspace "./meuslugares.xcworkspace"

# The name of the scheme which contains the UI Tests
 scheme("meuslugaresUITests")

# Where should the resulting screenshots be stored?
  output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
  clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
